# Generated by Django 5.1.4 on 2024-12-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_contactus_image_alter_contactus_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
